// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebReport.DataAccess;

namespace WebReport.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220329101103_newMigration")]
    partial class newMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("WebReport.Models.Attendance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("clock_in")
                        .HasColumnType("int");

                    b.Property<int?>("clock_out")
                        .HasColumnType("int");

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("date")
                        .HasColumnType("date");

                    b.Property<int?>("earliest_record")
                        .HasColumnType("int");

                    b.Property<int?>("latest_record")
                        .HasColumnType("int");

                    b.Property<int?>("subject_id")
                        .HasColumnType("int");

                    b.Property<int?>("worktime")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("subject_id");

                    b.ToTable("ATTENDANCE");
                });

            modelBuilder.Entity("WebReport.Models.Event", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double?>("age")
                        .HasColumnType("double");

                    b.Property<string>("camera_position")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<double?>("confidence")
                        .HasColumnType("double");

                    b.Property<int>("event_type")
                        .HasColumnType("int");

                    b.Property<double?>("fmp")
                        .HasColumnType("double");

                    b.Property<byte?>("fmp_error")
                        .HasColumnType("tinyint unsigned");

                    b.Property<double?>("gender")
                        .HasColumnType("double");

                    b.Property<int?>("group")
                        .HasColumnType("int");

                    b.Property<short?>("is_entrance")
                        .HasColumnType("smallint");

                    b.Property<int?>("mask_type")
                        .HasColumnType("int");

                    b.Property<int?>("pass_type")
                        .HasColumnType("int");

                    b.Property<string>("photo")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("pinyin")
                        .IsRequired()
                        .HasMaxLength(612)
                        .HasColumnType("varchar(612)");

                    b.Property<double?>("quality")
                        .HasColumnType("double");

                    b.Property<string>("real_name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("screen_id")
                        .HasColumnType("int");

                    b.Property<int?>("short_group")
                        .HasColumnType("int");

                    b.Property<int?>("subject_id")
                        .HasColumnType("int");

                    b.Property<string>("subject_photo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<short?>("subject_type")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("temperature")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("temperature_type")
                        .HasColumnType("int");

                    b.Property<int?>("timestamp")
                        .HasColumnType("int");

                    b.Property<string>("uuid")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("verification_mode")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("subject_id");

                    b.ToTable("EVENT");
                });

            modelBuilder.Entity("WebReport.Models.Subject", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("avatar")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("birthday")
                        .HasColumnType("date");

                    b.Property<string>("building")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("come_from")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<int?>("create_time")
                        .HasColumnType("int");

                    b.Property<string>("credential_no")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("credential_type")
                        .HasColumnType("int");

                    b.Property<string>("department")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("department_pinyin")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("description")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("domicile_address")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<long?>("domicile_city_code")
                        .HasColumnType("bigint");

                    b.Property<long?>("domicile_district_code")
                        .HasColumnType("bigint");

                    b.Property<long?>("domicile_province_code")
                        .HasColumnType("bigint");

                    b.Property<long?>("domicile_street_code")
                        .HasColumnType("bigint");

                    b.Property<int?>("education_code")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("end_time")
                        .HasColumnType("int");

                    b.Property<int?>("entrance_people_type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("date");

                    b.Property<string>("extra_id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<short?>("gender")
                        .HasColumnType("smallint");

                    b.Property<string>("house")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("house_rel_code")
                        .HasColumnType("int");

                    b.Property<string>("interviewee")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("interviewee_pinyin")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("inviter_id")
                        .HasColumnType("int");

                    b.Property<byte?>("is_use")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("job_number")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("marital_status_code")
                        .HasColumnType("int");

                    b.Property<int?>("mobile_os")
                        .HasColumnType("int");

                    b.Property<int?>("nation")
                        .HasColumnType("int");

                    b.Property<string>("nationality_code")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("origin")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("password_hash")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte?>("password_reseted")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("people_type")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("pinyin")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("purpose")
                        .HasColumnType("int");

                    b.Property<string>("real_name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("remark")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("residence_address")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<long?>("residence_city_code")
                        .HasColumnType("bigint");

                    b.Property<long?>("residence_district_code")
                        .HasColumnType("bigint");

                    b.Property<long?>("residence_province_code")
                        .HasColumnType("bigint");

                    b.Property<long?>("residence_street_code")
                        .HasColumnType("bigint");

                    b.Property<int?>("source")
                        .HasColumnType("int");

                    b.Property<int?>("start_time")
                        .HasColumnType("int");

                    b.Property<short>("subject_type")
                        .HasColumnType("smallint");

                    b.Property<string>("title")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long?>("update_time")
                        .HasColumnType("bigint");

                    b.Property<string>("village")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<byte?>("visit_notify")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("visited")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("wg_number")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("id");

                    b.ToTable("SUBJECT");
                });

            modelBuilder.Entity("WebReport.Models.Attendance", b =>
                {
                    b.HasOne("WebReport.Models.Subject", "Subject")
                        .WithMany("Attendance")
                        .HasForeignKey("subject_id");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("WebReport.Models.Event", b =>
                {
                    b.HasOne("WebReport.Models.Subject", "Subject")
                        .WithMany("Event")
                        .HasForeignKey("subject_id");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("WebReport.Models.Subject", b =>
                {
                    b.Navigation("Attendance");

                    b.Navigation("Event");
                });
#pragma warning restore 612, 618
        }
    }
}
